### ISSUE TITLE
Verify if the current version is the latest when starting up.

### ISSUE THREAD

**Issue by fabioz** [robocorp/robocorp#187]
Something like:

```
A new release of action-server is available: 2.40.1 → 2.42.1
To upgrade, run: ...
```

Note: need to detect how it was installed to provide instructions on how to upgrade.

**Comment by c02mo** [comment]
@fabioz Do we have any resources or indications on how the action-server is installed? 🤔 
The action-server can be just an executable which can be downloaded, right? That means we might not be able to detect any installation pattern.

**Comment by fabioz** [comment]
Right now the action server executable (the main one) is a go-program which extracts the actual action server to a given folder and runs it.

I think this would be the best place to tackle that.

@bogdancondurache did the work on that part and he can probably explain better than me.

**Comment by c02mo** [comment]
@fabioz Should this incorporate a question to the user if they want an update and do that for them? 🤔 
Not sure what the suggestion should be otherwise. They would need to manually download the executable and place it in the correct paths in order to work. Feels a bit more intuitive to have an auto-updater at user's approval.

**Comment by bogdancondurache** [comment]
@custompointofview I would advise against it. They don’t need to place it in path, they download the go-wrapper and that’s the one doing that. But the problem is the go wrapper would need to download the newer version including itself (in case any logic has been updated there) and replace itself with the new binary, calling that one. I think that’s valuable, but maybe at the moment it’s enough just to let the user know there’s a newer version

**Comment by c02mo** [comment]
Sure. I can only suggest that there is a new version. Still feels a bit like incomplete DX. 
The wrapper indeed does the copying, but in the issue the suggestion is that the user should do a specific action and my question was "what would that action be?". As such, I can also add as a suggestion to the user that they can download the executable from this URL based on their platform and run it. Would that suffice for now?
